
input:
  label: "player_2_shot"
  kafka:
    addresses:
      - broker:29092
    topics: 
      - bowling_turn
    target_version: 3.3.1
    consumer_group: "cg-player2-1"
    start_from_oldest: true

pipeline:
  processors:
    - mapping: |
        let rand1 = random_int(2)
        root = {}
        root.player = "Guille"
        root.player_id = 2
        root.bowls_points = $rand1 % 10 

output:
  resource: kafka_bowls_shots_results
