input:
  label: ""
  kafka:
    addresses:
      - broker:29092
    topics: 
      - benthos.mock_data.std
    target_version: 3.3.1
    consumer_group: "benthos-poc"
    checkpoint_limit: 1024
    start_from_oldest: true

pipeline:
  processors:
    - mapping: root = content().uppercase() #Convert to ups
output:
  stdout: {}
