input:
  label: ""
  generate:
    interval: 1s
    count: 0
    batch_size: 1
    mapping: |
      root.payload = if random_int() % 2 == 0 {
        {
          "type": "foo",
          "foo": "is yummy"
        }
      } else {
        {
          "type": "bar",
          "bar": "is gross"
        }
      }
      root.id = random_int().string().hash("sha1").encode("hex")
output:
  label: ""
  kafka:
    addresses:
      - broker:29092
    topic: benthos.mock_data
    target_version: 3.3.1
