input:
  label: ""
  kafka:
    addresses:
      - broker:29092
    topics: 
      - benthos.mock_data
    target_version: 3.3.1
    consumer_group: "benthos-poc-multi"
    checkpoint_limit: 1024

output:
  label: ""
  kafka:
    addresses:
      - broker:29092
    target_version: 3.3.1
    topic: 'benthos.output_data.${! json().payload.type }'
   
  
