input:
  kafka:
    addresses:
      - broker:9092
    topics: 
      - benthos.mock_data
    target_version: 3.3.1
    consumer_group: "benthos-poc"
    checkpoint_limit: 1024
    start_from_oldest: true

pipeline:
  processors:
    - mapping: |
        root.payload = json().payload.(bar|foo)
        root.meta.topic = meta("kafka_topic") 

output:
  label: ""
  kafka:
    addresses:
      - broker:29092
    target_version: 3.3.1
    topic: 'benthos.output_data'
   
  
