input:
  label: ""
  generate:
    interval: 1s
    count: 0
    batch_size: 1
    mapping: |
      root = if random_int() % 2 == 0 {
        {
          "type": "foo",
          "foo": "is yummy"
        }
      } else {
        {
          "type": "bar",
          "bar": "is gross"
        }
      }
output:
  resource: kafka

output_resources:
  - label: kafka
    kafka:
      addresses:
        - broker:9092
      topic: benthos.mock_data
      target_version: 3.3.1
